apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-demo0
  namespace: myapp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /api/v1/demo0/    ## url rewrite rule.
spec:
  ingressClassName: nginx     ## resource request will be passed to nginx ingress controller.
  rules:
  - host: is-yxy2.supor.com
    http:
      paths:
      - path: /demo0
        pathType: Prefix
        backend:
          service:
            name: solar-echoserver
            port:
              number: 8000
